query getDataSetById($id: ID!) {
  inbound {
    id
    dataSet(id: $id) {
      id
      name
      touched
      createdAt
      hasError
      latestErrorMessage
      errorType
      elasticTotal
      hasParsingWarnings
      expectedTotal
      lastPurgedAt
      lastPurgedBy
      isBridge
      isArchive
      hasQuarantineData
      archivedBy
      fileSize
      editableIndex
      editableIndexStatus
      extraFields
      extraComputedFields
      editableIndexAuthor
      undoPointer
      hashCheck
      externalTabs {
        id
        title
        description
        url
        __typename
      }
      invalidKeys {
        key
        original
        generatedName
        __typename
      }
      currentLoadedSize
      hasValidationParsingError
      hasValidationStoringError
      hasValidationMappingError
      hasValidationProcessingError
      failedLoadingTotal
      hasFailureInLoading
      isDeleteInProgress
      archivedByUser {
        id
        username
        __typename
      }
      lastPurgedByUser {
        id
        username
        __typename
      }
      author {
        id
        username
        __typename
      }
      annotationId
      annotation {
        id
        entityType
        originEntityCodeKey
        lastSubmissionPurgedByUser {
          id
          username
          __typename
        }
        lastSubmissionPurgedAt
        lastSubmissionPurgedBy
        annotationProperties {
          key
          vocabKey
          useAsEntityCode
          __typename
        }
        __typename
      }
      dataSourceId
      configuration
      dataSourceHasDuplicatedEntityType
      dataSource {
        id
        name
        type
        stopped
        connectorConfigurationId
        crashedDuringUpload
        dataSourceSet {
          id
          name
          __typename
        }
        __typename
      }
      filters {
        id
        name
        type
        inverse
        field
        value
        enabled
        dataSetId
        included
        createdAt
        __typename
      }
      operations {
        id
        name
        operation {
          id
          parameters
          __typename
        }
        filters {
          name
          type
          inverse
          field
          value
          enabled
          dataSetId
          included
          createdAt
          __typename
        }
        field
        count
        __typename
      }
      originalFields
      stats {
        total
        successful
        failed
        bytes
        __typename
      }
      fieldMappings {
        originalField
        key
        id
        columnType
        columnSubType
        __typename
      }
      __typename
    }
    __typename
  }
}