mutation addPropertyMappingToCluedMappingConfiguration(
  $dataSetId: ID!
  $propertyMappingConfiguration: InputPropertyMappingConfiguration
  $extra: Boolean
) {
  management {
    addPropertyMappingToCluedMappingConfiguration(
      dataSetId: $dataSetId
      propertyMappingConfiguration: $propertyMappingConfiguration
      extra: $extra
    )
    __typename
  }
}