query cleanProjectDetail($id: ID!) {
  preparation {
    cleanProjectDetail(id: $id) {
      name
      rowCount
      createdDate
      lastCommittedDate
      lastCommittedBy
      createdBy
      id
      status
      query
      autoGenerateRules
      hasCleanChanges
      hasBeenCommitted
      providerProjectId
      includeDataParts
      hasRules
      description
      fields {
        type
        property
      }
      condition {
        condition
        rules {
          condition
          field
          objectTypeId
          operator
          type
          value
          rules
        }
      }
      __typename
    }
    __typename
  }
}
