mutation createConnection(
  $connectorId: ID
  $authInfo: JSON
  $accountDisplay: String
) {
  inbound {
    createConnection(
      connectorId: $connectorId
      authInfo: $authInfo
      accountDisplay: $accountDisplay
    ) {
      id
      __typename
    }
    __typename
  }
}