query getInstalledConnectors {
  inbound {
    id
    connectors {
      id
      name
      icon
      about
      authMethods
      createdDate
      domain
      guide
      icon
      isEnabled
      isNew
      properties
      supportsWebHooks
      type
      streamModes
      __typename
    }
    __typename
  }
}