mutation saveGlossaryTerm($term: InputGlossaryTerm) {
  management {
    id
    saveGlossaryTerm(term: $term) {
      id
      name
      categoryId
      category {
        id
        name
        __typename
      }
      active
      createdBy
      modifiedBy
      isEndorsedByCurrentUser
      ownedBy
      createdAt
      modifiedAt
      shortDescription
      certificationLevel
      userRating
      rating
      version
      ruleSet
      description
      isObsolete
      endorsedBy
      relatedTags {
        id
        name
        __typename
      }
      __typename
    }
    __typename
  }
}
