mutation createPartialAutoAnnotation(
  $dataSetId: ID!
  $originalFields: [String]
) {
  management {
    createPartialAutoAnnotation(
      dataSetId: $dataSetId
      originalFields: $originalFields
    )
    __typename
  }
}