mutation createRule($rule: InputCreateRule!) {
  management {
    id
    createRule(rule: $rule) {
      id
      name
      description
      isActive
      createdBy
      modifiedBy
      ownedBy
      __typename
    }
    __typename
  }
}