query getAllDataSourceSet($page: Int, $pageSize: Int, $searchName: String) {
  inbound {
    dataSourceSets(page: $page, pageSize: $pageSize, searchName: $searchName) {
      total
      data {
        id
        name
        author {
          id
          username
          __typename
        }
        createdAt
        updatedAt
        dataSources {
          id
          type
          name
          hasError
          latestErrorMessage
          errorType
          sql
          connectionStatus {
            connected
            errorMessage
            __typename
          }
          author {
            id
            username
            __typename
          }
          createdAt
          updatedAt
          dataSets {
            id
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}