query getAnnotationById($id: ID) {
  preparation {
    annotation(id: $id) {
      id
      isDynamicVocab
      name
      entityType
      nameKey
      descriptionKey
      originEntityCodeKey
      createdDateMap
      modifiedDateMap
      cultureKey
      origin
      versionKey
      beforeCreatingClue
      beforeSendingClue
      useStrictEdgeCode
      useDefaultSourceCode
      vocabularyId
      vocabulary {
        vocabularyName
        vocabularyId
        providerId
        keyPrefix
        __typename
      }
      entityTypeConfiguration {
        icon
        displayName
        entityType
        __typename
      }
      annotationProperties {
        displayName
        key
        vocabKey
        coreVocab
        useAsEntityCode
        useAsAlias
        useSourceCode
        entityCodeOrigin
        vocabularyKeyId
        type
        annotationEdges {
          id
          key
          edgeType
          entityTypeConfiguration {
            icon
            displayName
            entityType
            __typename
          }
          origin
          dataSourceGroupId
          dataSourceId
          dataSetId
          direction
          edgeProperties {
            id
            annotationEdgeId
            originalField
            vocabularyKey {
              displayName
              vocabularyKeyId
              isCluedInCore
              isDynamic
              isObsolete
              isProvider
              vocabularyId
              name
              isVisible
              key
              mappedKey
              groupName
              dataClassificationCode
              dataType
              description
              providerId
              mapsToOtherKeyId
              __typename
            }
            __typename
          }
          __typename
        }
        vocabularyKey {
          displayName
          vocabularyKeyId
          isCluedInCore
          isDynamic
          isObsolete
          isProvider
          vocabularyId
          name
          isVisible
          key
          mappedKey
          groupName
          dataClassificationCode
          dataType
          description
          providerId
          mapsToOtherKeyId
          __typename
        }
        validations {
          id
          displayName
          inverse
          parameters {
            key
            value
            __typename
          }
          __typename
        }
        transformations {
          filters {
            parameters {
              key
              value
              __typename
            }
            id
            displayName
            inverse
            __typename
          }
          operations {
            inverse
            parameters {
              key
              value
              __typename
            }
            id
            displayName
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
