query getDataSetById($id: ID!) {
  inbound {
    dataSet(id: $id) {
      id
      name
      touched
      createdAt
      hasError
      latestErrorMessage
      errorType
      elasticTotal
      expectedTotal
      lastPurgedAt
      lastPurgedBy
      lastPurgedByUser {
        id
        username
        __typename
      }
      author {
        id
        username
        __typename
      }
      annotationId
      annotation {
        originEntityCodeKey
        annotationProperties {
          key
          __typename
        }
        __typename
      }
      dataSourceId
      canBeDeleted
      configuration
      dataSource {
        id
        name
        type
        dataSourceSet {
          id
          name
          __typename
        }
        __typename
      }
      originalFields
      stats {
        total
        successful
        failed
        bytes
        __typename
      }
      fieldMappings {
        originalField
        key
        edges {
          edgeType
          dataSetId
          dataSourceId
          dataSourceGroupId
          entityType
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}