query entityTypeLayoutConfigurations(
  $searchName: String
  $pageNumber: Int
  $pageSize: Int
) {
  management {
    id
    entityTypeConfigurations(
      searchName: $searchName
      pageNumber: $pageNumber
      pageSize: $pageSize
    ) {
      data {
        ...EntityTypeConfiguration
        __typename
      }
      total
      __typename
    }
    __typename
  }
}

fragment EntityTypeConfiguration on EntityTypeLayoutConfiguration {
  active
  displayName
  entityType
  icon
  id
  layoutConfiguration
  pageTemplateId
  path
  route
  template
  type
  pageTemplate {
    displayName
    name
    pageTemplateId
    __typename
  }
  __typename
}
