query getRule($id: ID!) {
  management {
    id
    rule(id: $id) {
      id
      name
      description
      isActive
      createdBy
      modifiedBy
      ownedBy
      createdAt
      modifiedAt
      condition
      actions
      rules
      sourceDetail {
        id
        name
        type
        __typename
      }
      author {
        id
        username
        __typename
      }
      scope
      __typename
    }
    __typename
  }
}