query getVocabulary($id: ID!) {
  management {
    id
    vocabulary(id: $id) {
      ...Vocabulary
      isVocabularyOwner
      author {
        id
        username
        __typename
      }
      owners {
        id
        username
        roles
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment Vocabulary on Vocabulary {
  vocabularyId
  vocabularyName
  keyPrefix
  isCluedInCore
  entityTypeConfiguration {
    icon
    entityType
    displayName
    __typename
  }
  isDynamic
  isProvider
  isActive
  grouping
  createdAt
  providerId
  description
  connector {
    id
    name
    about
    icon
    __typename
  }
  __typename
}
