mutation saveCustomOriginClueMappingConfiguration(
  $annotationId: ID!
  $customOrigin: String
) {
  management {
    saveCustomOriginClueMappingConfiguration(
      annotationId: $annotationId
      customOrigin: $customOrigin
    )
    __typename
  }
}