mutation saveStream($stream: InputStream!) {
  consume {
    id
    saveStream(stream: $stream) {
      ...Stream
      __typename
    }
    __typename
  }
}

fragment Stream on Stream {
  id
  name
  isActive
  createdBy
  modifiedBy
  type
  modifiedAt
  createdAt
  ownedBy
  condition
  rules
  numberOfRecords
  rulesApplied
  containerName
  mode
  exportOutgoingEdges
  exportIncomingEdges
  author {
    id
    username
    __typename
  }
  __typename
}