trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Modules/CluedIn.Product.Toolkit
    exclude:
    - Modules/CluedIn.Product.Toolkit/tests

name: ${{ parameters.moduleName }} v${{ parameters.moduleVersion }} Publish

parameters:
- name: moduleVersion
  displayName: 'Module Version'
  type: string
  default: '*'
- name: moduleName
  displayName: 'Module Name'
  type: string
  default: CluedIn.Product.Toolkit
- name: publish
  type: boolean
  default: false

steps:
- pwsh: |
    Write-Host "I will run pester"
  displayName: Test Module

- pwsh: |
    $organisation = 'CluedIn-io'
    $feed = 'CluedIn'
    $packageId = '09015c9c-1088-4087-978a-77d79521e180'

    $uri = "https://feeds.dev.azure.com/${organisation}/_apis/Packaging/Feeds/${feed}/Packages/${packageId}/Versions?api-version=7.1-preview.1"
    $headers = @{Authorization = "Bearer ${env:SYSTEM_ACCESSTOKEN}"}
    $result = Invoke-RestMethod -Uri $uri -Headers $headers
    Write-Host "Current Version: $($result.value.version)"
    Write-Host "##vso[task.setvariable variable=currentVersion]$($result.value.version)"
  displayName: Get current version
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- pwsh: |
    $modulePath = "$(System.DefaultWorkingDirectory)/Modules/${{ parameters.moduleName }}"
    $artifactPath = '$(Build.ArtifactStagingDirectory)/'
    Copy-Item -Path $modulePath -Destination $artifactPath -Recurse
    Remove-Item -Path $artifactPath/${{ parameters.moduleName }}/tests -Force -Recurse
  displayName: Copy Module to artifact staging

- pwsh: |
    $ModulePath = '$(Build.ArtifactStagingDirectory)/${{ parameters.moduleName }}'
    Write-Host "Module Path: $ModulePath"

    [version]$currentVersion = '$(currentVersion)'
    Write-Host "currentVersion: $currentVersion"

    switch ('${{ parameters.moduleVersion }}') {
        '*' {
            Write-Host "Auto-Incrementing new version"
            [version]$newVersion =
                '{0}.{1}.{2}' -f $currentVersion.Major, $currentVersion.Minor, ($currentVersion.Build + 1)
        }
        default {
            [version]$newVersion = '${{ parameters.moduleVersion }}'
        }
    }
    Write-Host "newVersion: $newVersion"

    if ($newVersion -le $currentVersion) {
        throw "The specified version '$newVersion' is lower/equal to '$currentVersion'"
    }

    Update-ModuleManifest -Path $ModulePath/${{ parameters.moduleName }}.psd1 -ModuleVersion ${{ parameters.moduleVersion }}
    Write-Host "##vso[task.setvariable variable=MODULE_VERSION]$newVersion"
  displayName: Update Module Version

- task: NuGetCommand@2
  displayName: 'Nuget Pack'
  inputs:
    command: pack
    versioningScheme: byEnvVar
    versionEnvVar: MODULE_VERSION
    packagesToPack: $(Build.ArtifactStagingDirectory)/${{ parameters.moduleName }}
    packDestination: '$(Build.ArtifactStagingDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: PowershellModule

- task: NuGetCommand@2
  displayName: 'NuGet Push'
  condition: eq( ${{ parameters.publish }}, 'true' )
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'CluedIn'