# Backs up configuration from specified environment

trigger: none

name: ${{ parameters.organisation }}.${{ parameters.baseURL }} Backup ($(Date:yyyyMMdd)$(Rev:r))

parameters:
- name: baseURL
  displayName: 'Clued In Base URL'
  type: string
- name: organisation
  displayName: 'Clued In Organisation'
  type: string
- name: version
  displayName: 'Clued In Environment Version'
  type: string

#variables:
#- template: vars/vars.yaml

resources:
  repositories:
  - repository: codeRepo # Friendly name for ADO to use
    type: github
    endpoint: 'CluedIn-io' # Service connection
    name: 'CluedIn-io/CluedIn.Product.Toolkit' # Actual GitHub repo name
  - repository: backupRepo
    type: github
    endpoint: 'CluedIn-io'
    name: 'jjrcluedin/jjr-testbackups'

jobs:
- job: backupConfiguration
  displayName: Backup Configuration
  steps:
  - pwsh: Get-ChildItem -Path ENV:\

  #- task: AzureCLI@2
  #  displayName: 'Backup'
  #  inputs:
  #    azureSubscription: 'Your ADO Subscription Here'
  #    scriptType: pscore
  #    scriptPath: Scripts/Export-CluedInConfig.ps1
  #    scriptArguments: >-
  #      -BaseURL ${{ parameters.baseURL }}
  #      -Organisation ${{ parameters.organisation }}
  #      -Version ${{ parameters.version }}
  #      -BackupPath $(System.DefaultWorkingDirectory)/Backups
  
  - pwsh: |
      git checkout -b main





    workingDirectory: $(System.DefaultWorkingDirectory)