mutation changeConfigurationSettings($organizationId: ID!, $key: String!, $value: String!) {
  administration {
    id
    changeConfigurationSettings(
      organizationId: $organizationId
      key: $key
      value: $value
    )
    __typename
  }
}