mutation createAnnotationCode($annotationCode: InputAnnotationCode) {
  preparation {
    id
    createAnnotationCode(annotationCode: $annotationCode) {
      id
      __typename
    }
    __typename
  }
}