mutation createEntityTypeConfigurationV2($entityTypeConfiguration: String!) {
  management {
    createEntityTypeConfigurationV2(
      entityTypeConfiguration: $entityTypeConfiguration
    )
    __typename
  }
}