query getDataSetById($id: ID!, $includeStatusesByLogs: Boolean = false) {
  inbound {
    id
    dataSet(id: $id, includeStatusesByLogs: $includeStatusesByLogs) {
      id
      annotation {
        ...AnnotationFragment
        __typename
      }
      name
      touched
      createdAt
      hasError
      latestErrorMessage
      errorType
      hasReceivedData
      sanitizeUnicodes
      elasticTotal
      expectedTotal
      hasSubmissions
      lastPurgedAt
      isOwner
      lastPurgedBy
      isBridge
      isArchive
      hasQuarantineData
      hasPendingRecordsApproval
      lastSwitchedToDefaultMode
      supportsIngestionSourceId
      archivedBy
      fileSize
      editableIndex
      editableIndexStatus
      extraFields
      extraComputedFields
      logsRetentionPeriod
      logsRetentionEnabled
      submissionsRetentionPeriod
      submissionsRetentionEnabled
      editableIndexAuthor
      undoPointer
      hashCheck
      externalTabs {
        id
        title
        description
        url
        __typename
      }
      invalidKeys {
        key
        original
        generatedName
        __typename
      }
      currentLoadedSize
      hasParsingWarnings
      hasValidationParsingError
      hasValidationStoringError
      hasValidationMappingError
      hasValidationProcessingError
      hasValidationEnrichingError
      editModeElasticTotal
      failedLoadingTotal
      isDeleteInProgress
      archivedByUser {
        id
        username
        __typename
      }
      lastPurgedByUser {
        id
        username
        __typename
      }
      author {
        id
        username
        __typename
      }
      annotationId
      annotation {
        id
        entityType
        originEntityCodeKey
        annotationCodeSetup
        useEnricherOriginEntityCode
        lastSubmissionPurgedByUser {
          id
          username
          __typename
        }
        lastSubmissionPurgedAt
        lastSubmissionPurgedBy
        annotationProperties {
          key
          vocabKey
          useAsEntityCode
          type
          __typename
        }
        __typename
      }
      dataSourceId
      configuration
      schemaDriftProtection
      dataSourceHasDuplicatedEntityType
      sourceOriginalFields {
        name
        dataSetId
        createdAt
        updatedAt
        __typename
      }
      dataSource {
        id
        name
        type
        stopped
        connectorConfigurationId
        crashedDuringUpload
        canBeDeleted
        landingZone {
          entityType
          vocabKeyPrefix
          origin
          originField
          autoMap
          autoSubmission
          useEnricherOriginEntityCode
          supportConfidenceScore
          confidenceScoreEnabled
          minConfidenceScore
          maxConfidenceScore
          confidenceAutoApprovalEnabled
          confidenceAutoThreshold
          confidenceQuarantineEnabled
          confidenceQuarantineThreshold
          entityTypeConfiguration {
            icon
            displayName
            entityType
            __typename
          }
          vocabularyConfiguration {
            vocabularyName
            vocabularyId
            providerId
            keyPrefix
            __typename
          }
          __typename
        }
        fileMetadata {
          fileName
          sanitizeUnicodes
          __typename
        }
        dataSourceSet {
          id
          name
          __typename
        }
        __typename
      }
      filters {
        id
        name
        type
        inverse
        field
        value
        enabled
        dataSetId
        included
        createdAt
        __typename
      }
      validations {
        id
        dataSetId
        name
        field
        operationDefinition
        createdAt
        updatedAt
        advancedValidation
        operation {
          id
          parameters {
            key
            value
            __typename
          }
          __typename
        }
        count
        invalid
        valid
        inverse
        required
        __typename
      }
      operations {
        id
        name
        operation {
          parameters {
            key
            value
            __typename
          }
          __typename
        }
        filters {
          name
          type
          inverse
          field
          value
          enabled
          dataSetId
          included
          createdAt
          __typename
        }
        field
        count
        __typename
      }
      originalFields
      stats {
        total
        successful
        failed
        bytes
        __typename
      }
      fieldMappings {
        originalField
        key
        id
        columnType
        columnSubType
        __typename
      }
      onlyUpdateClueHeadVersion
      quarantineCleaningJobInProgress
      __typename
    }
    __typename
  }
}

fragment AnnotationFragment on EntityAnnotation {
  id
  annotationCodeSetup
  isDynamicVocab
  name
  entityType
  previewImageKey
  nameKey
  descriptionKey
  originEntityCodeKey
  createdDateMap
  modifiedDateMap
  cultureKey
  origin
  versionKey
  beforeCreatingClue
  beforeSendingClue
  useStrictEdgeCode
  useDefaultSourceCode
  vocabularyId
  vocabulary {
    vocabularyName
    vocabularyId
    providerId
    keyPrefix
    __typename
  }
  entityTypeConfiguration {
    icon
    displayName
    entityType
    __typename
  }
  annotationProperties {
    key
    vocabKey
    coreVocab
    useAsEntityCode
    useAsAlias
    useSourceCode
    entityCodeOrigin
    vocabularyKeyId
    type
    annotationEdges {
      id
      key
      edgeType
      entityTypeConfiguration {
        icon
        displayName
        entityType
        __typename
      }
      origin
      dataSourceGroupId
      dataSourceId
      dataSetId
      direction
      edgeProperties {
        id
        annotationEdgeId
        originalField
        vocabularyKey {
          displayName
          vocabularyKeyId
          isCluedInCore
          isDynamic
          isObsolete
          isProvider
          vocabularyId
          name
          isVisible
          key
          mappedKey
          groupName
          dataClassificationCode
          dataType
          description
          providerId
          mapsToOtherKeyId
          __typename
        }
        __typename
      }
      __typename
    }
    vocabularyKey {
      displayName
      vocabularyKeyId
      isCluedInCore
      isDynamic
      isObsolete
      isProvider
      vocabularyId
      name
      isVisible
      key
      mappedKey
      groupName
      dataClassificationCode
      dataType
      description
      providerId
      mapsToOtherKeyId
      __typename
    }
    validations {
      id
      displayName
      inverse
      parameters {
        key
        value
        __typename
      }
      __typename
    }
    transformations {
      filters {
        parameters {
          key
          value
          __typename
        }
        id
        displayName
        inverse
        __typename
      }
      operations {
        inverse
        parameters {
          key
          value
          __typename
        }
        id
        displayName
        __typename
      }
      __typename
    }
    __typename
  }
  lastSubmissionPurgedByUser {
    id
    username
    __typename
  }
  lastSubmissionPurgedAt
  lastSubmissionPurgedBy
  __typename
}