query getDataSetById($id: ID!) {
  inbound {
    id
    dataSet(id: $id) {
      id
      name
      touched
      createdAt
      hasError
      latestErrorMessage
      errorType
      hasReceivedData
      sanitizeUnicodes
      elasticTotal
      hasParsingWarnings
      expectedTotal
      canResetMapping
      hasSubmissions
      lastPurgedAt
      isOwner
      lastPurgedBy
      isBridge
      isArchive
      hasQuarantineData
      hasPendingRecordsApproval
      supportsIngestionSourceId
      archivedBy
      fileSize
      editableIndex
      editableIndexStatus
      extraFields
      extraComputedFields
      logsRetentionPeriod
      logsRetentionEnabled
      submissionsRetentionPeriod
      submissionsRetentionEnabled
      editableIndexAuthor
      undoPointer
      hashCheck
      externalTabs {
        id
        title
        description
        url
        __typename
      }
      invalidKeys {
        key
        original
        generatedName
        __typename
      }
      currentLoadedSize
      hasValidationParsingError
      hasValidationStoringError
      hasValidationMappingError
      hasValidationProcessingError
      editModeElasticTotal
      hasSubmissions
      failedLoadingTotal
      isDeleteInProgress
      archivedByUser {
        id
        username
        __typename
      }
      lastPurgedByUser {
        id
        username
        __typename
      }
      author {
        id
        username
        __typename
      }
      annotationId
      annotation {
        id
        entityType
        originEntityCodeKey
        lastSubmissionPurgedByUser {
          id
          username
          __typename
        }
        lastSubmissionPurgedAt
        lastSubmissionPurgedBy
        annotationProperties {
          key
          vocabKey
          useAsEntityCode
          type
          __typename
        }
        __typename
      }
      dataSourceId
      configuration
      dataSourceHasDuplicatedEntityType
      dataSource {
        id
        name
        type
        stopped
        connectorConfigurationId
        crashedDuringUpload
        fileMetadata {
          fileName
          sanitizeUnicodes
          __typename
        }
        dataSourceSet {
          id
          name
          __typename
        }
        __typename
      }
      filters {
        id
        name
        type
        inverse
        field
        value
        enabled
        dataSetId
        included
        createdAt
        __typename
      }
      validations {
        id
        dataSetId
        name
        field
        operationDefinition
        createdAt
        updatedAt
        advancedValidation
        operation {
          id
          parameters {
            key
            value
            __typename
          }
          __typename
        }
        count
        invalid
        valid
        inverse
        required
        __typename
      }
      operations {
        id
        name
        operation {
          id
          parameters {
            key
            value
            __typename
          }
          __typename
        }
        filters {
          name
          type
          inverse
          field
          value
          enabled
          dataSetId
          included
          createdAt
          __typename
        }
        field
        count
        __typename
      }
      originalFields
      stats {
        total
        successful
        failed
        bytes
        __typename
      }
      fieldMappings {
        originalField
        key
        id
        columnType
        columnSubType
        __typename
      }
      onlyUpdateClueHeadVersion
      __typename
    }
    __typename
  }
}