mutation saveDataBaseConfigurationForDataSource(
  $id: ID!
  $configuration: JSON
) {
  inbound {
    saveDataBaseConfigurationForDataSource(
      id: $id
      configuration: $configuration
    )
    __typename
  }
}