mutation saveConnectorConfiguration(
  $connectorConfiguration: InputConnectorConfiguration
) {
  inbound {
    saveConnectorConfiguration(
      connectorConfiguration: $connectorConfiguration
    ) {
      id
      helperConfiguration
      __typename
    }
    __typename
  }
}